
# GitHub Actions Workflow: Sync Docs to Wiki
#
# This workflow automatically copies the contents of the docs/ folder to the GitHub Wiki repository
# for this project. It runs on every push to main or dev, or can be triggered manually.
#
# Steps:
# 1. Checks out the main repository.
# 2. Sets up the git user for commits.
# 3. Clones the Wiki repository using a token (see below for permissions).
# 4. Syncs docs/ to the wiki/ directory, overwriting existing wiki content.
# 5. Commits and pushes changes to the Wiki if there are any.
#
# Note: For write access to the Wiki, use a Personal Access Token (PAT) with 'repo' scope
# and add it as the WIKI_PUSH_TOKEN secret. Replace GH_TOKEN with WIKI_PUSH_TOKEN in the env section if needed.

name: Sync Docs to Wiki

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - dev

jobs:
  sync-wiki:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        # Checks out the main project repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Git user
        # Configures git user for automated commits
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Clone Wiki repository
        # Clones the GitHub Wiki repository using a token with write access
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Use WIKI_PUSH_TOKEN if PAT is required
        run: |
          git clone https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}.wiki.git wiki

      - name: Sync docs/ to wiki
        # Copies all files from docs/ to the wiki/ directory, deleting removed files
        run: |
          rsync -av --delete docs/ wiki/

      - name: Commit and push changes to Wiki
        # Commits and pushes changes to the Wiki repository if there are any
        run: |
          cd wiki
          git add .
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Sync docs/ to wiki [automated]"
            # Ensure remote is set to the wiki repo before pushing
            git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}.wiki.git
            git push origin HEAD:master
          fi
